[project]
name = 'dynamic-amm'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.flexiswap-core]
path = 'contracts/flexiswap-core.clar'
clarity_version = 2
epoch = 2.5

[contracts.flexiswap-math]
path = 'contracts/flexiswap-math.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
